# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Highbyte
locale: "en-US"
#email: highbyte[at]outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Home page of Highbyte. Software developer mainly in the .NET space, with interests in DevOps, application architecture, home automation, and gaming. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://highbyte.se" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: highbyte
github_username:  highbyte

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
#theme: jekyll-theme-slate
#theme: minima
#theme: jekyll-theme-minimal
#theme: jekyll-theme-midnight
#theme: jekyll-theme-leap-day
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#-------------------------------------------------
# Settings for gem "jekyll-titles-from-headings"
#-------------------------------------------------
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

#-------------------------------------------------
# Settings for theme "minimal_mistakes"
#-------------------------------------------------
minimal_mistakes_skin: default
author:
  name   : "Highbyte"
  avatar : "https://avatars1.githubusercontent.com/u/871085?s=460&u=3c5dc719d637e8fa879e039eb68f463bdf8f4868&v=4"
  bio    : "Software developer mainly in the .NET space, with interests in DevOps, application architecture, home automation, and gaming."
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://highbyte.se"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/highbyte/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/highbyte/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/christercederborg/"

footer:
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://highbyte.se"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/highbyte/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/highbyte/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/christercederborg/"

include:
  - _pages   

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/